const fs=require('fs'),vm=require('vm'),assert=require('assert');
const els={};const element=id=>els[id]??=({innerHTML:'',textContent:'',style:{},classList:{add(){},remove(){},toggle(){}},value:''});
const ctx={console,localStorage:{getItem(){return null},setItem(){}},document:{getElementById:element,querySelectorAll(){return []},querySelector(){return null}},navigator:{},scrollTo(){},setTimeout(){},Math,Number,JSON};
for(const id of ['suggest','cards','head','nav','filters','heading','subtitle'])ctx[id]=element(id);
vm.createContext(ctx);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8').match(/<script>([\s\S]*)<\/script>/)[1],ctx);
vm.runInContext(`
S.week=[];S.persons=2;
const curry=R.find(r=>r.sourceUrl?.includes('Ddwh1MVvL4a'));
assertTest=()=>{};
S.week=[curry.id];
if(shoppingTotals()['mosselen|g']!==500)throw Error('2 persons should get 500g of source 1000g/4');
if(!missingShopping()['kokosmelk|onbekend'])throw Error('missing coconut amount lost');
if(!renderShop() && document.getElementById('shopping').innerHTML.includes('NaN'))throw Error('NaN shown');
S.persons=4;if(shoppingTotals()['mosselen|g']!==1000)throw Error('4 persons must get 1000g');
const pasta=R.find(r=>r.sourceUrl?.includes('DdBYSwpPALx'));
S.week=[pasta.id,curry.id];
if(shoppingTotals()['olijfolie|el']!==undefined)throw Error('unknown base servings should not be scaled');
if(!missingShopping()['olijfolie|onbekend'].notes.some(n=>n.includes('8 el')))throw Error('source amount not preserved');
if(!ingredientLabel(pasta,pasta.ingredients.find(i=>i[0]==='olijfolie')).includes('8 el'))throw Error('detail source amount');
if(filtered('Snel').some(r=>r.time===null))throw Error('unknown times included as quick recipes');
openR(pasta.id,'week');
if(!document.getElementById('detail').innerHTML.includes("show('week')"))throw Error('return to week');
if(!document.getElementById('detail').innerHTML.includes(pasta.sourceUrl))throw Error('source missing');
if(document.getElementById('detail').innerHTML.includes('null min'))throw Error('unknown time formatting');
S.week=R.slice(0,9).map(r=>r.id);renderWeek();if(document.getElementById('weekList').innerHTML.includes('undefined'))throw Error('week longer than seven days');
S.week=[1,curry.id];renderShop();if(document.getElementById('shopping').innerHTML.includes('NaN'))throw Error('mixed known/unknown list broken');
if(new Set(R.map(r=>r.id)).size!==R.length)throw Error('duplicate ids');
`,ctx);
console.log('PASS: scaling, unknown quantities, source amounts, quick filter, details, week navigation, mixed grocery list, unique IDs');
